# =========================
# APPLICATION NAME
# =========================
spring.application.name=quantity-measurement-app


# =========================
# MYSQL (RAILWAY) DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# JPA / HIBERNATE CONFIGURATION
# =========================


# =========================
# H2 CONSOLE (DISABLED)
# =========================
spring.h2.console.enabled=false

# =========================
# SWAGGER / OPENAPI CONFIGURATION
# =========================
springdoc.swagger-ui.path=/quantity-measurement-app

# =========================
# SPRING BOOT ACTUATOR CONFIGURATION
# =========================
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# =========================
# JWT CONFIG
# =========================
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey12345
jwt.expiration=86400000

# =========================
# GOOGLE LOGIN
# =========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# =========================
# SERVER PORT
# =========================
server.port=8080

